### ISSUE TITLE
export SQLError

### ISSUE THREAD

**Issue by zdila** [mariadb-corporation/mariadb-connector-nodejs#100]
It would be nice to export `SQLError` so we could check in `catch` block `if (err instanceof SQLError) {...}`. Also it would be nice to reflect it in TypeScript type file. Now there is `MariaDbError` interface which can't be used in `instanceof`.

**Comment by rusher** [comment]
release with 2.3.1

**Comment by zdila** [comment]
Thanks, but in the type definition there is still something missing:

```js
interface SqlErrorConstructor extends ErrorConstructor {
  new (
    msg: string,
    fatal?: boolean,
    info?: { threadId?: number },
    sqlState?: string | null,
    errno?: number,
    additionalStack?: string,
    addHeader?: boolean,
  ): SqlError;

  readonly prototype: SqlError;
}

declare var SqlError: SqlErrorConstructor;
```

Otherwise it is impossible to do `err instanceof SqlError` (fails to compile).

@rusher could you please add it?
