### ISSUE TITLE
Force escapeId to emit backtick

### ISSUE THREAD

**Issue by raefaldhia** [mariadb-corporation/mariadb-connector-nodejs#101]
Hello,

I've just encountered error in my sql because i have `to` as column name although i had escaped the name with `escapeId`. it turns out that escapeId only emit the backtick if satisfied by some criteria.

**Comment by ottok** [comment]
Hello Raefaldhi!

You bug report is pretty much void of any actionable information. Please explain in detail what you tried to do, and what the result was, and what the expected result should have been.

Example reading: https://testlio.com/blog/the-ideal-bug-report/ and most importantly read https://github.com/mariadb-corporation/mariadb-connector-nodejs#contributing

**Comment by rusher** [comment]
[EscapeId implementation](https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/master/lib/misc/utils.js#L84) only use quote for identifiers that don't contain special characters. 

Current implementation doesn't handle identifier that are reserved words, only ensure escaping. 

That would make sense to always quote, to handle reserved words.

**Comment by rusher** [comment]
released in 2.3.0
