### ISSUE TITLE
Escaping query identifiers support lacking

### ISSUE THREAD

**Issue by SikoSoft** [mariadb-corporation/mariadb-connector-nodejs#104]
Someone brought this issue up on SO previously and I'm not sure they ever took your advice and created an issue for it, so here I am.

I would love to see support for escaping identifiers in queries (column names specifically, but certainly database names, table names would allow for even more robust code).

I have had 2 use cases for such a need; both of which result in me forcefully needing to uglify code that could have otherwise been short and sweet.

One such scenario is an API endpoint to update a very large and ever growing list of settings. The endpoint wants a setting ID and a value. The setting ID is a direct name of the column in the database table.

I can think of a number of scenarios I've been in too where I have different sets of similar data in different tables where I could have written less and more elegant code by place holding the table name.

**Comment by rusher** [comment]
There is 2 functions that permit 'manual' query escaping : 

- [connection.escape(value) → String](https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/master/documentation/promise-api.md#connectionescapevalue--string): escape parameter
- [connection.escapeId(value) → String](https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/master/documentation/promise-api.md#connectionescapeidvalue--string): escape identifier

if goal is for values, there is another package 'sql-template-strings' that permit to use variables : 

```
const SQL = require('sql-template-strings');
...
conn.query(SQL`SELECT author FROM books WHERE book_name = ${book} AND author = ${author}`);
```

Does is satisfy your needs or is there other use case not reported ?

**Comment by SikoSoft** [comment]
Yes, as a matter of fact, I have ended up going with connection.escapeId. It has allowed me to sufficiently elegant code I need without restructuring my data table.
