### ISSUE TITLE
query timeout not error and not work multipleStatements

### ISSUE THREAD

**Issue by zirill** [mariadb-corporation/mariadb-connector-nodejs#105]
Not error if timeout 
If multipleStatements=true (time out not work correctly)

```
try {
    await pool.query({sql: "SELECT SLEEP(5);SELECT SLEEP(5);", timeout: 3000});
} catch (e) {console.log(e.message)}
```

**Comment by rusher** [comment]
This is a limitation, SLEEP is a special case not affected by timeout (see [MDEV-18024](https://jira.mariadb.org/browse/MDEV-18024) ). 

If you think it's important vote for MDEV and explain you're use case.

**Comment by zirill** [comment]
Thanks for the link.

if there is no sleep, in multi query(multipleStatements) timeout total or for each?

```
try {
    await pool.query({sql: "SELECT proc(5);SELECT proc(5);", timeout: 3000});
} catch (e) {console.log(e.message)}
```

**Comment by rusher** [comment]
hmm, timeout won't work well for multi-queries. 
only the first query will be timeout
for multi statement, best is to write timeout manually , like : 

try {
    await pool.query({sql: "SET STATEMENT max_statement_time=XX FOR SELECT proc(5);SET STATEMENT max_statement_time=XX FOR SELECT proc(5);"});
} catch (e) {console.log(e.message)}

this clearly need an error when using multi-statements with description

**Comment by zirill** [comment]
it would be good if solved as

**for example**:

`mssql: ConnectionPool({requestTimeout: 3000})`
solution via connect, all connections are limited and get an error
also oracle

`potsgresql: server-file.conf`
Less convenient solution, since all requests are limited. option with mssql is more convenient

**Comment by rusher** [comment]
In the just release 2.3.0 version, timeout can be set on connection level : 

```
const mariadb = require('mariadb');
mariadb.createConnection({host: 'mydb.com', user: 'myUser', password: 'myPwd', timeout: 5000})
  .then(conn => {
    ...
  })
  .catch(err => {
    //handle connection error
  });
```
