### ISSUE TITLE
placeholders ?? support

### ISSUE THREAD

**Issue by KumaranM2040** [mariadb-corporation/mariadb-connector-nodejs#108]
Hi 

I have noticed that mariaDB connector does not support the ?? characters as placeholders for identifiers. Is this by design or on the "To do" list ? 

I thought that it would be good for compatibility with mysql connector. What are your thoughts ?

Kind regards
Kumaran M

**Comment by rusher** [comment]
It is by design. 

There is 2 reasons for that. 

- notation is confusing. 
	
	I generally really like the mysql API, but this is just one of the few cases where this is not the case. Take the example from [mysql](https://www.npmjs.com/package/mysql#escaping-query-identifiers):
	```
	var userId = 1;
	var columns = ['username', 'email'];
	var query = connection.query('SELECT ?? FROM ?? WHERE id = ?', [columns, 'users', userId], function (error, results, fields) {
	  if (error) throw error;
	  // ...
	});
	```
	first 'columns' variable here is not parameters but escape parameters, followed by another id to escape, then a parameter !? This isn't natural at all. 

- Second is performance: 

	This would actually be easy to do, but goal is always to perform better, and parsing has to be avoided client side as much as possible. 
	Even if there still is client parsing for now, there won't be in a near future. 


So in response, this has to be done manually. 
The simpliest solution is using template literals with connection.escapeId like: 
```
const myTable = "table'a"
con.query(`SELECT * FROM ${con.escapeId(myTable)} WHERE id = ?`, [myId])
  .then(res => { ... })
  .catch(err=> { ... });
```
This is more verbose, but at least it is not confusing and will permit further performance optimization.

**Comment by KumaranM2040** [comment]
Thank you Diego for the detailed response. I will close this ticket.
