### ISSUE TITLE
Awaiting any mariadb function triggers pending queries

### ISSUE THREAD

**Issue by brandonlee781** [mariadb-corporation/mariadb-connector-nodejs#110]
Repo demonstrating problem: https://github.com/brandonlee781/mariadb_error

The issue I've been running into is that I'm trying to push queries into an array to later be used in a Promise.all(). In the real world use case some of these rely on data from a separate query, but that's irrelevant to the issue.

We have an array of unresolved query promises when we create a new connection and run a query on this new connection. As soon as we await the creation of the new connection, the array of unresolved queries are all resolved/rejected. This array of queries and the connection they use are completely separate from the new connection, but they are still being triggered.

I've tested this on node version 12.13 and 13.8 and mariadb version 2.3.1 and 2.1.4.

**Comment by rusher** [comment]
I'm not sure to understands the issue well. You'll tell. 

If seems that the problem is just how promise are defined : 
```
async function main() {

  const promiseArray = [];
  promiseArray.push(db.query('SELECT 1'));
  promiseArray.push(db.query('SELECT 2'));
  promiseArray.push(db.query('SELECT 3'));
  promiseArray.push(db.query('SELECT """'));
  promiseArray.push(db.query('SELECT 4'));

  const num5 = await secondFunc();
  return await Promise.allSettled(promiseArray);
}
```

Problem here seems to be that first array of promise completion is not well handled, some query might finished before secondFunc finish.

one solution might be 
```
async function main() {

  const promiseArray = [];
  promiseArray.push(db.query('SELECT 1'));
  promiseArray.push(db.query('SELECT 2'));
  promiseArray.push(db.query('SELECT 3'));
  promiseArray.push(db.query('SELECT """'));
  promiseArray.push(db.query('SELECT 4'));
  let run1 = Promise.allSettled(promiseArray);
  const num5 = await secondFunc();
  return await run1 ;
}
```

**Comment by brandonlee781** [comment]
If I understand promises correctly (and it might be that I don't) the ones pushed in the array should stay pending until they are run in Promise.allSettled. In fact, if I push them all into the array and await ANY other, non-mariadb promise that is exactly what happens. Only when I await a mariadb promise does the array of promises get resolved without the awaiting.

The issue has arisen because in our case we have bad data. All of the db.queries are based on inputs outside of our control and occasionally result in invalid queries. But instead of handling errors on every individual query, we'd prefer to handle them all at once on the Promise.allSettled (hence the reason for it instead of Promise.all), but we have to perform other queries before we can get to that point. If the queries are being forced to resolve before the allSettled, we can't do that.

**Comment by zdila** [comment]
> If I understand promises correctly (and it might be that I don't) the ones pushed in the array should stay pending until they are run in Promise.allSettled

You don't :-). Promise executes immediately and not by awaiting it to resolve. They also resolve without need to await it. So `const p1 = db.query('SELECT 1')` starts the query execution immediately and `await p1` will only block if `p1` is not resolved yet in which case it will block until it is resolved.
