### ISSUE TITLE
`createConnection(string)` does not support URL-encoded credentials

### ISSUE THREAD

**Issue by cedx** [mariadb-corporation/mariadb-connector-nodejs#115]
In a URL, user/password must be URL-encoded if they contain special characters.
Let's say the password is `foo@bar`: the corresponding string is `foo%40bar`.

So if we use a connection string to open a connection, the user/password must be URL-decoded otherwise an error occurs:

```
mariadb.createConnection("mariadb://user:foo%40bar@localhost:3306/db");
# Error: (conn=9, no: 1045, SQLState: 28000) Access denied for user 'user'@'localhost' (using password: YES)
```

See: https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/master/lib/config/connection-options.js#L210
Credentials are passed as-is.

**Comment by rusher** [comment]
This will be part of 2.4.1 version with correction above
