### ISSUE TITLE
Cannot use placeholder with ORDER BY where unquoted value is required

### ISSUE THREAD

**Issue by Simonwep** [mariadb-corporation/mariadb-connector-nodejs#120]
First, thanks a lot for this great module! It's amazingly pleasant to work with :)

I have the following, simplified query I want to execute:
```sql
SELECT *
   FROM user
   ORDER BY ?
   LIMIT ?
   OFFSET ?
```
to do that I'm using placeholders to properly escape values (although escaping numbers is kinda unnecessary if they're already properly validated):

```js
const order = 'username';
const limit = 60;
const offset = 100;

const res = await db.query(`
    SELECT *
        FROM user
        ORDER BY ?
        LIMIT ?
        OFFSET ?
`, [order, limit, offset]);
```

The thing is now that the first `?` doesn't work because, if `escape` is also used internally, `escape('username')` returns `username` which results in the following query:
```sql
SELECT *
   FROM user
   ORDER BY 'username' # No error gets thrown (???) but for ORDER BY it's required for the value to be not put into quotes
   LIMIT 60 # OK
   OFFSET 100 # OK
```
A work-around in my case was inserting the value directly (and of course validating it on my own):
```js
const order = 'username';
const limit = 60;
const offset = 100;

const res = await db.query(`
    SELECT *
        FROM user
        ORDER BY ${order}
        LIMIT ?
        OFFSET ?
`, [limit, offset]);
```

Is that the 'correct' way of doing this or did I miss something in the documentation?

**Comment by rusher** [comment]
parameters will always be escaped, so you're right, string will be converted to string, 
your command look good.  

Just a thing though: since 'order' is a variable, to avoid any possible injection, [escapeId ](https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/master/documentation/promise-api.md#connectionescapeidvalue--string) is your friend: 
```
const order = 'username';
const limit = 60;
const offset = 100;

const res = await db.query(`
    SELECT *
        FROM user
        ORDER BY ${db.escapeId(order)}
        LIMIT ?
        OFFSET ?
`, [limit, offset]);
```

**Comment by rusher** [comment]
closing, since answer was given. (feel free to create another issue if this doesn't suit you)

**Comment by Simonwep** [comment]
Huh your first comment somehow got lost, thanks a lot! :D The extra escape utilities are definitely handy!
