### ISSUE TITLE
Cannot configure SSL certificate.

### ISSUE THREAD

**Issue by zommerberg** [mariadb-corporation/mariadb-connector-nodejs#123]
Hello, I am using mariaDB with a provider that offers a SSL certificate bundle. 
I have downloaded it and tried to set up.
My mariaDB pool setup looks like this.

```
const serverCert = [fs.readFileSync('./ssl-certificate.pem', 'utf8')]

export const pool = mariadb.createPool({
  host: process.env.MariaHost ,
  user: process.env.MariaUser ,
  password: process.env.MariaPassword ,
  database: process.env.MariaDatabase ,
  ssl: {
    ca: serverCert,
    rejectUnauthorized: process.env.NODE_ENV == 'developent' ? false : true,
  },
  connectionLimit: 15,
  dateStrings: true,
})
```

The error I get is ```Trying to connect with ssl, but ssl not enabled in the server``` (In Development)

Does anyone know where the problem comes from?

**Comment by rusher** [comment]
it seems server hasn't ssl configured. 
try this query `SHOW VARIABLES LIKE '%ssl%'` to check if have_ssl is enabled

**Comment by zommerberg** [comment]
@rusher  
I just checked and it works in production.
It just doesn't work locally but this is not a big deal.
have_ssl was enabled , maybe local setup was wrong.
