### ISSUE TITLE
Please help?

### ISSUE THREAD

**Issue by Mr-Smarty** [mariadb-corporation/mariadb-connector-nodejs#124]
This is a little embarrassing to ask, but can someone help with simply doing a query: SHOW TABLES then logging it to the console? I can't find a good tutorial for mysql/maridb anywhere, and none of the examples help either. Thanks if you can help :)

Note, `conn.query('SHOW TABLES', console.log)` doesn't work...

**Comment by rusher** [comment]
see [query](https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/master/documentation/promise-api.md#connectionquerysql-values---promise) documentation. 
query returns a promise. 

try something like   
```
    conn
      .query('SHOW TABLES')
      .then(res => {
        console.log(res);
      })
      .catch(error => {
        console.log(error);
      });

```

**Comment by Mr-Smarty** [comment]
Thanks a lot! That worked! Sorry for the confusion, I am following a tutorial for mysql, which obviously has its differences. Is there a way to do queries outside of the 
```mariadb.createConnection({ options })
.then(conn => { the code you gave me }) ``` ?
Because as of now, whenever I try conn.query elsewhere, it doesn't recognize it as a function. Sorry for my lack of knowledge regarding this. But thanks so far @rusher :)

**Comment by zommerberg** [comment]
@Mr-Smarty 
This is basic setup that you could use.
```
import 'dotenv/config'

import express from 'express'
const mariadb = require('mariadb')

export const pool = mariadb.createPool({
  host: process.env.MariaHost,
  user: process.env.MariaUser,
  password: process.env.MariaPassword,
  database: process.env.MariaDatabase,
  connectionLimit: 10,
  dateStrings: true,
})
process.on('uncaughtException', function (err) {
  console.error(err)
})

const app = express()

app.use(express.json())
app.use(express.urlencoded({ extended: true }))

app.post('/getUser', async (req, res) => {
  const { email } = req.body
  const cleanEmail = email.toLowerCase().trim()
  let connection
  try {
    connection = await pool.getConnection()
    const user = await connection.query(
      `SELECT email FROM users WHERE email = ?  LIMIT 1`,
      [cleanEmail]
    )

    res.json({
      user,
    })
  } catch (error) {
    console.log(error)
    res.json({ error: 'Internal Server Error' })
  } finally {
    if (connection) return connection.release()
  }
})

const port = process.env.PORT || 8080

app.listen(port, () => {
  console.log(`Server started at http://localhost:${port}`)
})
```
 When accessing any route that accesses your DB you should first get an available connection from the pool , perform a query and finally release the connection so it returns back to the pool.

**Comment by rusher** [comment]
@zommerberg it's totally right.
Just for information, for your specific example, if there is only one query, there is an alias pool.query that permit to get a connection, execute a query and release connection.
 
```
  let connection
  try {
    connection = await pool.getConnection()
    const user = await connection.query(
      `SELECT email FROM users WHERE email = ?  LIMIT 1`,
      [cleanEmail]
    )

    res.json({
      user,
    })
  } catch (error) {
    console.log(error)
    res.json({ error: 'Internal Server Error' })
  } finally {
    if (connection) return connection.release()
  }
```
can be slightly simplified :
```
  try {
    const user = await pool.query(
      `SELECT email FROM users WHERE email = ?  LIMIT 1`,
      [cleanEmail]
    )

    res.json({
      user,
    })
  } catch (error) {
    console.log(error)
    res.json({ error: 'Internal Server Error' })
  }
```

**Comment by zommerberg** [comment]
@rusher  This is a very good point!

**Comment by Mr-Smarty** [comment]
It's been a long time since this issue was opened and since then I have used a few different solutions. Recently I switched back to MariaDB but using TypeORM. I noticed this issue was still open so I wanted to come back and close it. Thanks for your help! :)
