### ISSUE TITLE
Type error on ssl in Connection object

### ISSUE THREAD

**Issue by Sparticuz** [mariadb-corporation/mariadb-connector-nodejs#126]
Just looking into this package and was setting it up in vscode. As I was setting it up, this error came up for me. The types say the ssl should be a string or a SecureContextOptions, however, the documentation says it can be a boolean. Which is correct? I can put together a pull request if needed.

https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/41d3926b1deed2fe10e601d13cd954a7f1654a66/types/index.d.ts#L233

https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/master/documentation/connection-options.md#configuration

**Comment by rusher** [comment]
Documentation is right : it can be boolean or [tls.SecureContextOptions ](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/612eff867bdabb475aec051e83b90846db393d6f/types/node/v11/tls.d.ts#L340) 

example : https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/master/test/integration/test-ssl.js#L166 

boolean is the basic option to set SSL when server is using well-known root Certificate Authorities, so not having to set anything client side but enabling SSL. 


(This is a difference from mysql that can have ["Amazon RDS"](https://www.npmjs.com/package/mysql#ssl-options) parameter)

**Comment by rusher** [comment]
closed as released in 2.5.0
