### ISSUE TITLE
How to properly get results from EXISTS query.

### ISSUE THREAD

**Issue by zommerberg** [mariadb-corporation/mariadb-connector-nodejs#127]
Hello, is it possible to simply get 0 or 1 from a EXISTS  query?

```
    const userHasValidRefreshTokenId = await connection.query(
      `SELECT EXISTS (SELECT * FROM users WHERE id = ? AND token_id = ? LIMIT 1)`,
      [payload.user_id, payload.token_id]
    )
    console.log(userHasValidRefreshTokenId)

    const freindExistSQl = `EXISTS (SELECT * FROM users WHERE id = ${payload.user_id} AND token_id = ${payload.token_id} LIMIT 1)`

    if (userHasValidRefreshTokenId[0][freindExistSQl] == 0) {
      console.log('token version changed')
      return res.status(403).send()
    }
```

The current response I get is :
![signaling3](https://user-images.githubusercontent.com/43446836/91937994-ce481b80-ecfb-11ea-8d39-9d0fabeaebc3.png)

The problem is that exists returns an array with an object which a key name same as the query name (notice i access the first element in the array with the query as a key).
It is really hard to access the final result this way.
Is it possible for the query to return directly 0 or 1 so I don't need to create a `validTokenSql` variable.

Thanks!

**Comment by rusher** [comment]
hi @zommerberg 
you can use alias like this : 
```
    const userHasValidRefreshTokenId = await connection.query(
      `SELECT EXISTS (SELECT * FROM users WHERE id = ? AND token_id = ? LIMIT 1) as a`,
      [payload.user_id, payload.token_id]
    )
    // userHasValidRefreshTokenId will then be  [{ a: 1 }] 
```
another solution that might interrest you is option [`rowsAsArray`](https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/master/documentation/promise-api.md#rowsasarray) that only return results as array, without key. 
```
    const userHasValidRefreshTokenId = await connection.query(
      { rowsAsArray: true, sql: `SELECT EXISTS (SELECT * FROM users WHERE id = ? AND token_id = ? LIMIT 1)` },
      [payload.user_id, payload.token_id]
    )
    // userHasValidRefreshTokenId will then be  [[1]] 
```

**Comment by zommerberg** [comment]
@rusher  Thank you! Exactly what I was looking for.
