### ISSUE TITLE
Prepared Statement Support

### ISSUE THREAD

**Issue by oliverdunk** [mariadb-corporation/mariadb-connector-nodejs#128]
Hi! Thanks for your work on this. I'm excited by what seems to be a very well written MySQL library for Node.JS.

I stumbled across connection.batch, and based on my reading of the code, it seems like passing a single set of values to this would be the equivalent of running a prepared statement. Do you agree? Is that the case regardless of MariaDB version? Are there any caveats, particularly in a security sense?

Also, just generally, I'm curious if you still plan on implementing prepared statements? It's a blocker for me switching to this library, as they provide a lot of reassurance.

**Comment by rusher** [comment]
Hi @oliverdunk. 

Batch isn't exactly prepared statement.

prepared statement is : prepare + execute + close. 
In term of mysql protocol, that is [COM_STMT_PREPARE](https://mariadb.com/kb/en/com_stmt_prepare/) + [COM_STMT_EXECUTE](https://mariadb.com/kb/en/com_stmt_execute/) + [COM_STMT_CLOSE](https://mariadb.com/kb/en/3-binary-protocol-prepared-statements-com_stmt_close/)

Batch use an optimized version of "execute" passing groups of parameters. 
In term of protocol : [COM_STMT_PREPARE](https://mariadb.com/kb/en/com_stmt_prepare/) + [COM_STMT_BULK_EXECUTE](https://mariadb.com/kb/en/com_stmt_bulk_execute/) + [COM_STMT_CLOSE](https://mariadb.com/kb/en/3-binary-protocol-prepared-statements-com_stmt_close/) 

Batch behavior differs depending on the server: 
* use COM_STMT_BULK_EXECUTE If server support it (> 10.2.7 MariaDB server)
* rewrite query if possible: example `batch('insert into ab (i) values (?)', [[1],[2]])` will result in sending only one query `insert into ab (i) values (1), (2)`
* many queries if cannot be rewritten. Example query that cannot be rewritten `INSERT INTO TABLE(col1) VALUES (?) ON DUPLICATE KEY UPDATE col2=?`

About security, problems come when people build SQL command with parameters themself. Using SQL with placeholder and parameters that are escaped client side doesn't change anything in term of security. 

Using real prepared statement is on the roadmap. There is not so much difference in terms of performance between statement/prepared statement for now. Differents tasks like this [one](https://jira.mariadb.org/browse/MDEV-19237 ) will change that in 10.6 (next year). At that time for sure, connector will implement real prepared statement

**Comment by vaintroub** [comment]
SQL with placeholder and parameter replacement by the library is much, than concatenating strings in the application, because library would do correct escaping, and this prevents the SQL injection.
That much about security.

**Comment by oliverdunk** [comment]
Thanks for the reply @rusher! @vaintroub, I completely agree. Using what the library has is a far better idea than doing something myself.

That said, for me personally, I still see benefits to prepared statements other than performance. I agree that if the client side escaping is perfect, there's no noticeable difference between the two. However, security is hard, and the possibility of obscure edge cases is a worry. There are examples of where escaping wasn't enough, like [this one](https://vigilance.fr/vulnerability/MySQL-SQL-injection-via-multi-byte-characters-5885). I'm sure you know what you're doing and have tried your best to write something robust - but it's easier to say "let's just let the server handle that", and I'd feel more comfortable using a library that takes that approach. It would likely be enough to give this the edge over "mysql", which currently looks appealing because so many more eyes have looked over the code.

One more bonus - if new syntax was ever added (perhaps unlikely for SQL), using prepared statements would make sure that the handling of untrusted data was updated alongside my server.

In summary, I understand if you're not planning to look at this right now. However, if any of this convinces you to take a look sooner, I would be very excited!

Speaking about batch statements upfront was perhaps a silly idea, so I've left coming back to that until now. I don't know much about the MySQL protocol, but because it uses COM_STMT_PREPARE, it seems like it takes the same approach where the query to execute is sent separately to the data? This makes me think that in 10.2.7+, as long as [this function](https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/38c49b1c0736d7702267a574ef620dafc66b5ab7/lib/connection.js#L661) returns true, there's no escaping done by the client and I'm essentially running a prepared statement? It's probably unwise to do that, since it'd be using something in a way it wasn't intended, and maybe there are risks there too - but I just thought it was interesting to see that at least some of the prepared statements work is here already.

**Comment by vaintroub** [comment]
it is possible to escape any data, and the old bugs do not prove the opposite. In fact, you server has much higher probability to crash, or run out of memory if you use server-side prepared statements . I do not think it would be too far fetched to say that is that there are many more bugs related to server side prepared statements month filed in a month, than there are overall bugs related to client-side prepared statements parsing in all connectors in all the years of MySQL and MariaDB existence

**Comment by rusher** [comment]
Prepare statement are now supported, in 3.x version. 
See [prepare](https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/maintenance/3.x/documentation/promise-api.md#connectionpreparesql--promise) and [execute](https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/maintenance/3.x/documentation/promise-api.md#connectionexecutesql-values--promise) documentation.

Release is actually in beta (3.0.0-beta), but GA will be later this year
