### ISSUE TITLE
When to use conn.end() and conn.release() and max_connections limit

### ISSUE THREAD

**Issue by zommerberg** [mariadb-corporation/mariadb-connector-nodejs#129]
Hello, recently I've tried to connect my production database to a Database Management Tool (phpMyAdmin and HeidiSQL).
However I got an error saying "max_user_connection" exceeded current value 10" , the app itself is used only by me and every connection is released to the pool.
Is it possible that I need to end the connection instead of releasing it somewhere?
Why would I get the  `max_user_connection` error? The only thing that comes in mind is the incorrect usage of conn.release().

My current setup looks like this:

```
import 'dotenv/config'

import express from 'express'
const mariadb = require('mariadb')

export const pool = mariadb.createPool({
  host: process.env.MariaHost,
  user: process.env.MariaUser,
  password: process.env.MariaPassword,
  database: process.env.MariaDatabase,
  connectionLimit: 10,
  dateStrings: true,
})
process.on('uncaughtException', function (err) {
  console.error(err)
})

const app = express()

app.use(express.json())
app.use(express.urlencoded({ extended: true }))

app.post('/user', async (req, res) => {
  const { email } = req.body
  const cleanEmail = email.toLowerCase().trim()
  let connection
  try {
    connection = await pool.getConnection()
    const user = await connection.query(
      `SELECT email FROM users WHERE email = ?  LIMIT 1`,
      [cleanEmail]
    )

    res.json({
      user,
    })
  } catch (error) {
    console.log(error)
    res.json({ error: 'Internal Server Error' })
  } finally {
    if (connection) return connection.release()
  }
})

const port = process.env.PORT || 8080

app.listen(port, () => {
  console.log(`Server started at http://localhost:${port}`)
})
```

This is the simplified version, but every endpoint is exactly like `/user` . I get the connection from the pool variable and I release it to the pool in `finally` after the query is completed.
Is this approach incorrect? Do I need to actually end the connection somewhere?
The weird part is that I am able to execute queries from the app without any issues, I just can't connect to the GUI tool.
Thanks!

**Comment by zommerberg** [comment]
In case I have already created 10 connections in the cache and 9 of them are available I still will not be able to use them in order to connect to the database via a GUI tool. I will be able to execute queries from the app but I am not able to connect to the GUI tool.

This means I need to create a new connection every time I connect to the GUI tool and close it  every time I exit the tool?
Or will it close itself automatically?

In case I use the user with 10 connections in production, does that mean that I need to have another user that is used in order to manipulate the database via GUI tool?
What is the optimal strategy for connecting to a GUI tool for a production database? If I understood it correctly even if I set the connection limit to 10000 , the pool will still be filled at some point, then how do I connect?

@rusher

**Comment by rusher** [comment]
>In case I have already created 10 connections in the cache and 9 of them are available I still will not be able to use them in order to connect to the database via a GUI tool.
right, those 9 +1 connections are active, so if max_user_connection  is reached, you'll not be able to create another connection.

There can be lots of way to solve this. 
connectionLimit is set to 10, so pool will not have more than 10 connections. 
increasing max_user_connection will solve the issue. but creating a different user is by far a better solution (different rights, identification, ...)

**Comment by zommerberg** [comment]
Thanks, I also spoke with my DB provider. A solution he suggested was to change the `connectionLimit` to 9. This way if my max connection limit is 10, I will always have one available connection that I could use for GUI management.
