### ISSUE TITLE
Is it possible to perform other operations during batch insert ?

### ISSUE THREAD

**Issue by zommerberg** [mariadb-corporation/mariadb-connector-nodejs#130]
Hello, I have a place where I need to insert a lot of items at once, however before inserting them for each item I need to get  a specific column with a SELECT statement from another table example:

```
for (let item of bigListOfItems) {
    try {
      const { id, other_data_column } = item
      await connection.query(
        `INSERT INTO my_table(id,another_id) VALUES (?,
              (SELECT id from another_table WHERE stuff = other_data_column)`,
        [id, other_data_column]
      )
    } catch (error) {
      console.log(error)
    }
  }

```

I need something like INSERT INTO SELECT statement but with batches so I avoid making a `for of loop`
```
connection.batch(
        `INSERT INTO my_table(id,another_id)
                VALUES (?,?)`,
        [[10,`SELECT id FROM another_table WHERE stuff = 10`],[12,`SELECT id FROM another_table WHERE stuff = 15`] ....]
      )
```

Is this possible to achieve? If not is there a better strategy regarding loops?

**Comment by rusher** [comment]
probably something like 
```
connection.batch(
        'INSERT INTO my_table(id,another_id) SELECT ?, id FROM another_table WHERE stuff = ?', 
        [[10, 10], [12, 15] ....]
      );

```

https://stackoverflow.com/ is a more appropriate place for this kind of question, since it's more or less only SQL

**Comment by zommerberg** [comment]
I managed to insert it this way:

```
connection.batch(
        'INSERT INTO my_table(id,another_id) VALUES( ?, (SELECT id FROM another_table WHERE stuff = ?)) ', 
        [[10, 10], [12, 15] ....]
      );
```

**Comment by zommerberg** [comment]
Not sure if this relates to the library or the batch operation itself however when I do that it find the correct  id and instead of assigning it only to the appropriate row it assigns it to every created row in the batch operation
