### ISSUE TITLE
Batch insert results with incorrect reference id.

### ISSUE THREAD

**Issue by zommerberg** [mariadb-corporation/mariadb-connector-nodejs#134]
Hello, I insert multiple values in a batch while on every insert I make an additional request to a separate table so I get a specific Id.
```
connection.batch(
        'INSERT INTO my_table(id,another_id) VALUES( ?, (SELECT id FROM another_table WHERE stuff = ?)) ON DUPLICATE KEY UPDATE another_id=VALUES(another_id) ', 
        [[10, 10], [12, 15] ....]
      );
```

As you can see I have a `SELECT id FROM another_table WHERE stuff = ?` in my values list, but instead of being executed on every insert it is executed only on the first insert so I end up with:

```
id:10
another_id:1231

id:12
another_id:1231

id:13
another_id:1231

...
```
The `another_id` is only correct for the first insert, it just gets copied down to every other insert without being executed, how can I fix that? Thanks!

**Comment by rusher** [comment]
reported server side : https://jira.mariadb.org/browse/MDEV-23864
as a workaround until correction, set `bulk` option to false, or avoid inner select

**Comment by rusher** [comment]
closing since this is not a connector issue, but server. follow https://jira.mariadb.org/browse/MDEV-23864 for more information
