### ISSUE TITLE
JSON values behave differently with different MariaDB versions

### ISSUE THREAD

**Issue by whitebyte** [mariadb-corporation/mariadb-connector-nodejs#136]
I have two databases with identical content but different versions, 10.3 and 10.5. When I `SELECT` JSON fields from 10.3, they arrive as strings, so I do `JSON.parse` on them. But the very same code returns already parsed JS array when run against 10.5.
I don't see any JSON-related breaking changes in MariaDB 10.4 and 10.5 changelogs, so it seems like a bug for me.

My connection is pretty standard, nothing fancy here:
```js
    pool = await mariadb.createPool({
        host              : config.dbHost,
        port              : config.dbPort,
        user              : config.dbUser,
        password          : config.dbPassword,
        database          : config.dbName,
        multipleStatements: true,
        checkDuplicate    : false,
        connectionLimit   : 80,
        permitLocalInfile : true
    });

```
Exact output of `SELECT VERSION()`:

```10.3.16-MariaDB-1:10.3.16+maria~bionic-log```
```10.5.5-MariaDB-1:10.5.5+maria~focal```

Connector version: 2.4.2

**Comment by rusher** [comment]
MariaDB consider JSON as String with some specific constraint / validity following SQL requirement.
 
Since https://jira.mariadb.org/browse/MDEV-17832 (MariaDB 10.5.2) server send clearly data type as JSON. 
Driver can return resultset JSON value as JSON or String according to `autoJsonMap` option value.

This is missing in documentation. I need to add this !

**Comment by whitebyte** [comment]
Wow, that was fast! Thanks for the heads up

**Comment by outbackStack** [comment]
I'm not sure how you have fixed this @whitebyte, but I'm running into the same issues with not getting the JSON, but instead string with `autoJsonMap: true`.

Nodejs connector `3.0.0-beta`
Server version: `10.6.4-MariaDB`

Example query: `SELECT JSON_OBJECT("id", 1, "name", "Monty");`

**Comment by whitebyte** [comment]
In my case the connector stopped recognizing data in one table as JSON after importing data into said table from another DB. Despite the fact the imported data was a valid JSON, the connector returned it as string.

Given that MariaDB doesn't have a real JSON type and simply aliases it as LONGTEXT, I wonder how the connector distinguishes between JSON and string.
