### ISSUE TITLE
Maria DB Timezone not Set

### ISSUE THREAD

**Issue by lukegalea16** [mariadb-corporation/mariadb-connector-nodejs#139]
I am setting my DB config for Sequelize as follows:
```
dialect: "mariadb",
dialectOptions: {
  timezone: "America/Los_Angeles"
},
```

However my created_at and updated_at timestamps are according to the time zone of the server not how I set the time zone.
What could I be doing wrong?

**Comment by rusher** [comment]
Looking at sequelize source, date is stringify before sending to driver, so this is done at sequelize level. 
changing to sequelize timezone to "America/Los_Angeles" must solve your issue : 

```
dialect: "mariadb",
timezone: "America/Los_Angeles",

```

**Comment by lukegalea16** [comment]
I get a warning `warning: please use IANA standard timezone format ('Etc/GMT+8')`

**Comment by rusher** [comment]
correction: 
solution is : 
```
dialect: "mariadb",
dialectOptions: {
  timezone: "America/Los_Angeles"  //for reading from database
},
timezone: "America/Los_Angeles", //for writing to database

```
I'll submit a PR to sequelize, since this doesn't make sense to set timezone multiple times.
