### ISSUE TITLE
Connections Open for Long Time error out with "connection closed"

### ISSUE THREAD

**Issue by josiahbryan** [mariadb-corporation/mariadb-connector-nodejs#142]
I have a long running socket server that is runs for days at a time. Eventually new connections (mostly on Mondays) error out with `Cannot execute new commands: connection closed` when calling the `query()` method on the connection. (It works for days at a time, then after weekends mostly, it throws that error.)

How can I catch / reconnect automatically and then retry the query so that clients don't fail authentication? 

Right now my only solution is restart the server - not ideal!

**Comment by rusher** [comment]
If connection are not used for some time, server can close the socket. 
Client will knows socket state only when writing to socket. 

That behaviour depend on [`wait_timeout`](https://mariadb.com/kb/en/server-system-variables/#wait_timeout) (default to 28800s = 8h)

There is different way to handle that : 
* use pool: after not being used for some time (`idleTimeout` default 30 minutes), connection are closed (new one might be created depending on minimum required connection).
* if you use only connection, change session wait_timeout to a more appropriate value, like : 
```
const connection = await mariadb.createConnection({host: 'mydb.com', user: 'myUser', password: 'myPwd', initSql: 'set @@wait_timeout = 604800' });
```

**Comment by josiahbryan** [comment]
Thanks, will try the second option, as my code already has a pool call, not
sure now that should work to alleviate the problem though haha

**Comment by rusher** [comment]
_closing, since this is default server behavior_
feel free to create a new task related to this one if you think this can be better
