### ISSUE TITLE
Array with Empty string 2.5.2 vs 2.4.2

### ISSUE THREAD

**Issue by el9in** [mariadb-corporation/mariadb-connector-nodejs#144]
WORK in 2.4.2
```
const result = '';
const some = [[result],[result]]
INSERT INTO `vk_group_bans`(`text`) VALUES ?), some
```
But not work in 2.5.2
```
Return "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '''' at line 1"
___
Empty string '' error
```

**Comment by rusher** [comment]
2.5.0 correct some incompatibility with mysql / mysql2 drivers. Now, arrays are returned escaped as list, not list in parenthesis. 
You can either revert this change setting connection option `[arrayParenthesis](https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/master/documentation/connection-options.md#other-options)` to true. 

Correction is to add parenthesis. So for your example : 
```
await connection.query('INSERT INTO `vk_group_bans`(`text`) VALUES (?)), some);
```

**Comment by el9in** [comment]
Thanks for help.
