### ISSUE TITLE
Missing type for "result" callback parameter

### ISSUE THREAD

**Issue by tnyeanderson** [mariadb-corporation/mariadb-connector-nodejs#148]
When using callbacks, the "result" parameter does not have a defined type. Is it possible to add a type for this?

**Comment by rusher** [comment]
Can you explain more what do you expect there ? 
is it only documentation or something else ? 
Typescript definition rely on promise implementation, so i expect this is not what you asking for.

**Comment by tnyeanderson** [comment]
Yupp, this was a misunderstanding on my part.... sorry for the noise :)
