### ISSUE TITLE
How to insert records?

### ISSUE THREAD

**Issue by TheGP** [mariadb-corporation/mariadb-connector-nodejs#154]
Ok I figured out after 15 mins how to insert with INSERT INTO table VALUE (?, ?) with an increment ( u have to do (null, value))
But how to insert if I have pairs key -> value in an object?

**Comment by outbackStack** [comment]
say you have an object like this
`const object1 = {
  key: '1',
  value: 'something
};
`

you need to turn this into an array first...something like this 
`
[[1, something]]
`

then use batch to insert bulk values

**Comment by rusher** [comment]
Usually with increment, you don't even list the value : 
table 
```
CREATE TABLE my_table(
            id int(11) unsigned NOT NULL AUTO_INCREMENT,
            val varchar(256),
            PRIMARY KEY (id)
);
```
then

If you use auto_increment, field has not even to be there. 
```
const myObj = { myKey: value };
await conn.query('INSERT INTO my_table (val) VALUE (?)', [myObj.myKey]);
```
Stackoverflow is usually a better support for question like that.

**Comment by TheGP** [comment]
> Stackoverflow is usually a better support for question like that.
How would they know it if the module has no documentation?

Both of your examples didn't work, so I switched to mysql2 and it worked with `INSERT INTO events_log SET ?`, much better lib.

**Comment by outbackStack** [comment]
is the table `events_log` a JSON type?

**Comment by outbackStack** [comment]
Have a look at this discussion on #155. I think the explanations are on there.

**Comment by rusher** [comment]
Closing, since that's mariadb/mysql SQL than driver related.
Feel free to create a new conversation linking to this one if that's not the case
