### ISSUE TITLE
ER_FUNC_INEXISTENT_NAME_COLLISION error

### ISSUE THREAD

**Issue by Congelli501** [mariadb-corporation/mariadb-connector-nodejs#156]
I migrate a nodejs api from mysql2 to mariadb. The app use generated sql queries.
I found a strange & reproductible SQL error that only happens with mariadb.

I'm using Mariadb 10.5.9 (latest mariadb:10.5 docker image) for my tests.

```javascript
const mariadb = require('mariadb');

(async () => {
	const pool = await mariadb.createPool({
		host: 'localhost',
		user: '<user>',
		database: '<db>'
	});

	await pool.query('SELECT "ok"'); // Required to reproduce the issue

	try {
		// The space between the SUM and ( seems to trigger the issue
		const res = await pool.query('SELECT SUM ( 1 ) AS `total`');
		console.log(res);
	} finally {
		await pool.end();
	}
})().catch(e => {
	console.error(e);
	process.exitCode = 1;
});
```

This code will output the following error:
```
SqlError: (conn=223, no: 1630, SQLState: 42000) FUNCTION db.SUM does not exist. Check the 'Function Name Parsing and Resolution' section in the Reference Manual
sql: SELECT SUM ( 1 ) AS `sum` - parameters:[]
...
  fatal: false,
  errno: 1630,
  sqlState: '42000',
  code: 'ER_FUNC_INEXISTENT_NAME_COLLISION'

```

The problem seems to be trigerred by the space between `SUM` and `( 1 )`. Indeed, the code will work this this query:
```sql
SELECT SUM( 1 ) AS `total`
```

But the original query will work ok with mysql2 or the command line mariadb client.

Even more strangely (which gave me a hard time reproducing the issue), removing the `SELECT "ok"` will make the second query work.

The code will also work with the `AVG` function instead of `SUM`.

This issue is trivial to fix on my side (remove the space after the aggregation function) but I found it worth mentionning.

**Comment by rusher** [comment]
I've created a [server issue ](https://jira.mariadb.org/browse/MDEV-25897) for that. thanks for reporting that. 
If you have lots of space to remove, as a workaround, you can set pool configuration `resetAfterUse` to false. Connection will not be reset in pool (mysql/mysql2 doesn't reset connection, that's the reason of the difference)
