### ISSUE TITLE
Latest version: 2.5.4

### ISSUE THREAD

**Issue by outbackStack** [mariadb-corporation/mariadb-connector-nodejs#162]
Hi guys,

I'm not able to update from the NPM registry with the latest release (2.5.4). I can only see 2.5.3 now. Also, do you know how I could test out the beta version? I tried it with `npm install mariadb@3.0.0-beta` and it doesn't work.

**Comment by rusher** [comment]
that's an error during when publishing, it will be corrected in the next few hours

**Comment by rusher** [comment]
ok, version are available now. 
2.5.4 is now latest release, and beta is available with specific version `npm install mariadb@3.0.0-beta` or `npm install mariadb@beta`

thanks for reporting it !
