### ISSUE TITLE
Pool.query(undefined) doesn't release connection

### ISSUE THREAD

**Issue by Drejerdk** [mariadb-corporation/mariadb-connector-nodejs#163]
If pool.query is called without a valid SQL parameter, the connection will never get realsed.

It took me quite a while to figure out that I was missing a comma between the array parameter and the query in the line below, which caused my code to leak connections.
```pool.query(`SELECT COUNT(*) FROM tx.tx_push_messages WHERE id= ? AND msgType= "stop-reminder";`[id])```

Is this a bug, or is there some reason the `processTaskPromise` and `processTaskCallback` only calls `conn.releaseWithoutError();` if the SQL parameter is set?

**Comment by rusher** [comment]
Even if query is expect to be defined, driver has to handle those cases. 
I've created https://jira.mariadb.org/browse/CONJS-170 to handle that

**Comment by rusher** [comment]
done. Correction will be available in 2.5.5, 3.0.1-RC
