### ISSUE TITLE
MariaDB Query in Node Project Failing

### ISSUE THREAD

**Issue by Muirik** [mariadb-corporation/mariadb-connector-nodejs#168]
I am making various SQL queries from within my Node backend in order to retrieve data, and then streaming that to a React front-end app to be able print PDFs. This had been working without issue for a couple of months. Then sometime last week it stopped working.

FYI, I am running "mariadb": "2.1.0".

The error I get is this:

`Error: (conn=273264, no: 4078, SQLState: HY000) Illegal parameter data types int and row for operation '='`

IMPORTANT: The failure only happens if there is more than one record being fed in. In other words, to be clear, if this will end up matching to one record, it works. If it matches to more than one then it fails.

The function in question where the failure is happening looks like this:

```
  async getTargetedSessionTypes(sessionIDs) {
    const query = `SELECT DISTINCT * FROM (${this.notesQuery} AND notes_details.id_number IN (?)) AS sessionQuery`;
    const values = [sessionIDs];
    console.log('query: ', query); // I can see this in the console
    console.log('values: ', values); // I can see these in the console
    const result = await this.db.query(query, values); // This fails
    if (result.length > 0) {
      console.log('0 - result in getTargetedSessionTypes: ', result);
      return Transform.transformNoteSessions(result);
    }
    return [];
  }
```

What I have noticed is that, if I try to plug in the query and values that are generated here in SQL Workbench directly, I don't get any errors. The query will run without issue. But within my Node environment this function is failing.

**Comment by rusher** [comment]
Error is send from server. This is an SQL error. 
Without parameters this is unclear what cause this. 

You always can debug this adding  `debug: true` to your connection options. 
This will permit to give the exact SQL command, that you can try with you prefered SQL editor. 

anyway, stackoverflow is a better solution to handle this kind of issue, so closing it here.
