### ISSUE TITLE
Missing leakDetectionTimeout option in type files

### ISSUE THREAD

**Issue by JohnXLivingston** [mariadb-corporation/mariadb-connector-nodejs#169]
Hello,

The option leakDetectionTimeout for the createPool function is missing in type files. See PoolConfig type:
 https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/f68ecb313d64a25d41f5a6c68b2fdb04789431bc/types/index.d.ts#L329

Best regards,
John

**Comment by rusher** [comment]
thanks for reporting it !
correction will be in next release 2.5.5 and 3.0.1-rc
