### ISSUE TITLE
Issue in starting Mariadb docker

### ISSUE THREAD

**Issue by anurag53** [mariadb-corporation/mariadb-connector-nodejs#172]
Hi,

I had installed MariaDB using docker (attached volumes for dbroots and MySQL) on an Ubuntu server. I then took a backup of my dbroots and MySQL directory.

I have now moved these backups on another Ubuntu server and tried to spin a new MariaDB docker attaching my dbroots and MySQL as a volume. 

Please find the command which I used for the same:

pathVar="/mnt/backup"
mkdir -p $pathVar/database/mysql/db
mkdir -p $pathVar/database/mariadb/data
mkdir -p $pathVar/database/mariadb/data1
chmod -R 777 $pathVar
docker rm --force mariadb
docker run -d --restart=always -p 3306:3306 --name mariadb -v $pathVar/database/mysql/db:/usr/local/mariadb/columnstore/mysql/db -v $pathVar/database/mariadb/data:/usr/local/mariadb/columnstore/data -v $pathVar/database/mariadb/data1:/usr/local/mariadb/columnstore/data1 mariadb:10.3.28

After this, when I tried logging in to my MariaDB, I and getting the following error message.

ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/usr/local/mariadb/columnstore/mysql/lib/mysql/mysql.sock' (2)

I checked the issue, it's not able to create mysql.sock.

Can you pls help me to resolve this? 

Thank you so much.

**Comment by anurag53** [comment]
HI,

The issue has been resolved. 

1. I spun the new docker by attaching the same dbroot and MySQL directory as a volume
2. Because of SELinux security, it was not allowing to create a MySQL socket. I used the --security-opt label=disable to prevent that.

Here is my final docker run command:
docker run -d --restart=always -p 3306:3306 --name mariadb --security-opt label=disable -v $pathVar/database/mysql/db:/usr/local/mariadb/columnstore/mysql/db -v $pathVar/database/mariadb/data:/usr/local/mariadb/columnstore/data -v $pathVar/database/mariadb/data1:/usr/local/mariadb/columnstore/data1 mariadb:10.3.28

Thank you.

**Comment by rusher** [comment]
I'm no expert to docker( usually using TCP port).
Closing since marked as resolved without indicating if this is the recommended solution.
