### ISSUE TITLE
DDL statements are not replicating

### ISSUE THREAD

**Issue by lukeescude** [mariadb-corporation/mariadb-connector-nodejs#174]
Hello,

Using the MariaDB NodeJS Connector version 2.5.4 - Apparently after a while (pool of connections has been running for more than 6 hours or so) DDL statements like ALTER TABLE/ADD COLUMN will not replicate with Galera.

We updated from 10.4.18 to 10.4.21 last night hoping the bug was with MariaDB and/or Galera, but that doesn't appear to be the case.

**Comment by rusher** [comment]
Driver has nothing to do with replication. If command is send to server and response is ok, that means server has handle command. Driver doesn't send command to all servers, only to one server. When driver receive a response, that means server handle this. For example, with galera, response is returned only if a majority of server did confirm the change, so from that point galera's servers are ok. 

Replication is then asynchronous or semisynchronous. How replica behave is totally depending on your installation/configuration.
All i can tell is that driver is not involved in replication at all.

I'm not a replication expert at all. better to ask on stackoverflow your issue.
