### ISSUE TITLE
Return of SELECT

### ISSUE THREAD

**Issue by riccardomerlo** [mariadb-corporation/mariadb-connector-nodejs#175]
Hello, 
How can I retrieve only the rows from a SELECT query, instead of getting both single rows and META ? Even deconstructing the result object does not work. Thank you

**Comment by johnrijoy** [comment]
how did you do it?

**Comment by riccardomerlo** [comment]
in the end it worked without doing anything...

this is my service:

``` 
const result = await this.connection.query(queryString);

if (result.length === 0) {
  return null;
}
return result; 
```

this is where i call it:
``` 
const obj = await this.dbService.get();
     
if (obj) {
     const res = obj[0]
} 
```
and res contains just my data, what happened I think was due some console log or something
