### ISSUE TITLE
this.throwError() is not a function

### ISSUE THREAD

**Issue by matpen** [mariadb-corporation/mariadb-connector-nodejs#177]
The error
`this.throwError(new Error("unknown charset : '" + value + "'"), info);`

originates under some conditions at [this line](https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/bc9f6c73bb9f1ffd3306f31bb061965b67b7f447/lib/cmd/command.js#L144), possibly because `this` is referenced within a [static function](https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/bc9f6c73bb9f1ffd3306f31bb061965b67b7f447/lib/cmd/command.js#L116).

**Comment by rusher** [comment]
thanks for releving that issue. corrected in develop banch, and will be part of 2.5.6 release
