### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by blue-predator** [mariadb-corporation/mariadb-connector-nodejs#178]
My server config
![image](https://user-images.githubusercontent.com/53546590/138491334-921e53b7-a2d0-44f9-b96b-7a4acc99db13.png)

I'm using the following dialectOption for timezone:
![image](https://user-images.githubusercontent.com/53546590/138489995-5610858c-98f1-434c-b25a-42895f546126.png)

For timestamps after 20:00:00 a +3:00 is added.
![image](https://user-images.githubusercontent.com/53546590/138489898-64e0471e-2e12-4eb4-b078-e89ab3214ccb.png)

Results from the database
![image](https://user-images.githubusercontent.com/53546590/138489729-929f216d-ca9d-47cd-b04d-bbf50c8c1f3c.png)

Is this a bug or am I missing something?

**Comment by rusher** [comment]
POSIX compatibility requires that the offsets are inverted. Therefore, Etc/GMT-X will have an offset of +X and Etc/GMT+X will have an offset of -X. strange, but this is the reason. 

    console.log(moment.tz('etc/GMT-3').format('YYYY-MM-DD HH:mm ZZ'));
    // 2021-12-09 18:18 +0300
    console.log(moment.tz('america/Paramaribo').format('YYYY-MM-DD HH:mm ZZ'));
    // 2021-12-09 12:18 -0300


better to use a locality based identifiers like 'america/Paramaribo' that avoid this kind of error.

**Comment by blue-predator** [comment]
@rusher I been looking into this again and notice that this happens when using the MIN() and MAX() function.
For the start_scan_time and end_scan_time I'm using those functions for a type TIMESTAMP column.

![image](https://user-images.githubusercontent.com/53546590/198115920-08882694-d8eb-43ae-b3b6-2e115c752d22.png)

**Comment by rusher** [comment]
I need more informations. 
First have you changed timezone to `america/Paramaribo` ?
What are the initial data ?
