### ISSUE TITLE
docs with promises might have issues

### ISSUE THREAD

**Issue by kswope** [mariadb-corporation/mariadb-connector-nodejs#181]
just one example of many, copied from the README.md

```
pool.getConnection()
    .then(conn => {
    
      conn.query("SELECT 1 as val")
        .then(rows => { // rows: [ {val: 1}, meta: ... ]
          return conn.query("INSERT INTO myTable value (?, ?)", [1, "mariadb"]);
        })
        .then(res => { // res: { affectedRows: 1, insertId: 1, warningStatus: 0 }
          conn.release(); // release to pool
        })
        .catch(err => {
          conn.release(); // release to pool
        })
        
    }).catch(err => {
      //not connected
    });
```

In the two identical lines above:
```
conn.release(); // release to pool
```

If my understanding of promises is sound, these two lines are shooting blanks, since conn.release() is each returning a promise, which are not being resolved.

It should be
```
return conn.release(); // release to pool
```
```

**Comment by rusher** [comment]
it works, promises automagically return a Promise.resolve() then, but this is not very clear. 
 
It even doesn't make sense to use pre async/await example anymore. anyway, doc and readme updated to use async examples that clarify use : https://github.com/mariadb-corporation/mariadb-connector-nodejs/commit/0ec7eeaa9e1224520129bba0a0f78f33d0fca072

**Comment by kswope** [comment]
Oh, so .release isn't async at all?  Then what's the point of returning a resolved promise?  (in my debugging I probably didn't look close enough to notice it wasn't a "pending", I just saw "promise" and assumed it was pending.)

If releasing a promise isn't async then maybe that would explain all the jest errors I was getting about having to kill lingering processes when I tried replacing mysql2 with mariadb.  Switched back to mysql2 and they were all gone.

**Comment by rusher** [comment]
release() clearly return a promise (it might query a 'rollback' command for example)

I mean that:
```
       .then(res => { 
          conn.release(); // release to pool
        })
```
is exactly the same than 
```
       .then(res => { 
          conn.release(); // release to pool
          return Promise.resolve();
        })
```
You're clearly right, sorry for misleading !

**Comment by rusher** [comment]
>If releasing a promise isn't async then maybe that would explain all the jest errors I was getting about having to kill lingering >processes when I tried replacing mysql2 with mariadb. Switched back to mysql2 and they were all gone.

About that i'm very curious. mysql2 and mariadb Pool implementation completly differ, but normally for the best. If there is any malfunction, i would gladly hear more about that.

**Comment by kswope** [comment]
I just set up everything again to look at the mouseovers types so I'm assuming they are correct.


Here's the difference between returning promise from a then and not returning,
without the return statement the asyncronicity is lost.  Which is why I'm assuming there's something wrong with the promises doc.  Or maybe the lib itself, which might explain why I was having lingering connection errors

```
let p = new Promise((res) => {
  console.log("in process of doing stuff");
  setTimeout(() => {
    res("did stuff");
  }, 3000);
});

// Start a new promise chain with resolve()
Promise.resolve()
  .then(() => {
    p; // NO RETURN
  })
  .then((x) => {
    // RUNS IMMEDIATELY
    console.log("then ", x);
  });

// Start a new promise chain with resolve()
Promise.resolve()
  .then(() => {
    return p; // RETURN
  })
  .then((x) => {
    // RUNS WHEN PROMISE IS RESOLVED
    console.log("then", x);
  });


```

**Comment by rusher** [comment]
Closing (documentation as been clarified since, see [doc](https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/master/documentation/promise-api.md#connectionrelease--promise))
