### ISSUE TITLE
Script throws ER_LOCAL_INFILE_WRONG_FILENAME error when trying to load data into table from local XML file

### ISSUE THREAD

**Issue by digeomel** [mariadb-corporation/mariadb-connector-nodejs#183]
Hello,
I have described the issue in detail in this StackOverflow question:

https://stackoverflow.com/questions/70084900/mariadb-node-js-script-throws-er-local-infile-wrong-filename-error-when-trying-t?noredirect=1

To save you an extra click I will repeat it here:

I have a node.js script which is connecting to a local MariaDB server, creating some tables, and then attempting to load some data into them by executing a SQL query like this:

```
LOAD XML LOCAL INFILE 'C:\\path\\to\\some_data.xml'
INTO TABLE some_data
ROWS IDENTIFIED BY '<data>';
```

The script fails with an error like:

```
SqlError: (conn=60, no: 45034, SQLState: 45034) LOCAL INFILE wrong filename. 'C:\path\to\some_data.xml' doesn't correspond to query LOAD XML LOCAL INFILE 'C:\\path\\to\\some_data.xml'
INTO TABLE some_data
ROWS IDENTIFIED BY '<data>';. Query cancelled. Check for malicious server / proxy
```

The node.js script code is like:
```
const pathToXmlFile = path.resolve(__dirname, '../some_data.xml')
   .replace(/\\/g, '\\\\');
   // .replace(/\\/g, '/'); 
// none of the above work, and neither does no escaping at all
query = `LOAD XML LOCAL INFILE '${pathToXmlFile}'
         INTO TABLE some_data
         ROWS IDENTIFIED BY '<data>';`;
```

I tried escaping the path with forward slashes (I'm running the script through Git Bash), the error remains the same, only the way the path is displayed changes. I have set `permitLocalInfile: 'true'` on the MariaDB client connection and `local_infile=1` on both the `[mysqld]` and `[client]` sections of `my.ini`. The node.js connection user has the FILE privilege.

Node version is 16.13.0, MariaDB npm module version is 2.5.5, all running on the same machine with Windows 10 (MariaDB server too, on localhost).

**The above query works perfectly fine when executed from HeidiSQL.**

I have debugged the issue and it seems to come down to this `validateFilename` function:

https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/519e4ab1a87c40cf1c0bbd75d1377baecf944959/lib/misc/parse.js#L1007

I have tested the regular expression here and it seems to me that it is wrong:

https://regex101.com/r/JtyetM/1

It looks like it fails even for a simple filename with no path delimeters. Upon close inspection it looks like it doesn't cover the `LOAD XML` case at all, only `LOAD DATA`, but I'm not sure this is the only problem.

**Comment by rusher** [comment]
this is corrected with commit https://github.com/mariadb-corporation/mariadb-connector-nodejs/commit/45aece2925507d0e4d556722bfe3bdc85b7094e7, and will be part of 2.5.6
