### ISSUE TITLE
Please update the documentation. Since Node v10.0.0, for-await-of is available.

### ISSUE THREAD

**Issue by ganlvtech** [mariadb-corporation/mariadb-connector-nodejs#189]
https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/0ec7eeaa9e1224520129bba0a0f78f33d0fca072/documentation/promise-api.md#L763

Since Node v10.0.0, for-await-of is available.

```javascript
async function doSomeQuery() {
  const readable = connection.queryStream("SELECT * FROM mysql.user");
  for await (const row of readable) {
    console.log(row);
  }
}
```

See <https://nodejs.org/api/stream.html#readablesymbolasynciterator>

**Comment by rusher** [comment]
closing since corrected last year
