### ISSUE TITLE
Update query with '?'

### ISSUE THREAD

**Issue by karolpiernikarz** [mariadb-corporation/mariadb-connector-nodejs#191]
I have a question regarding the following UPDATE statement. Is this actually possible? If not, can you please suggest a solution? 

` await sqlConnection.query('UPDATE MyTable SET ? WHERE id='${id}'', updateObject);`

**Comment by rusher** [comment]
question mark correspond to parameters.
if you need query to be variables, better to use Template literals, like:

`await sqlConnection.query(`UPDATE MyTable SET ${sqlConnection.escapeId(updateObject)} WHERE id=?`, [id]);
`

this way, updateObject is properly escaped, and parameter is at his place
