### ISSUE TITLE
Disconnect event not caught

### ISSUE THREAD

**Issue by Galienna** [mariadb-corporation/mariadb-connector-nodejs#195]
Hi,

The 3.0.0 release seems to have introduced a bug that wasn't there in 2.5.6.

**Scenario**
- Using the promise API
- Create a connection pool
- Get a connection
- Perform some requests
- Release connection
- Shutdown the DB server
- Error ER_CONNECTION_KILLED is sometimes caught in the error event of the connection, sometimes not
- Error ER_SOCKET_UNEXPECTED_CLOSE is sometimes caught in the error event of the connection, sometimes not
- One more ER_SOCKET_UNEXPECTED_CLOSE is raised but I'm unable to catch it, thus my node process crashes. It doesn't get caught by the error event handler that I added to the connection.

Exact same code and scenario works fine with 2.5.6

Good luck and thank you for the lib :)

**Comment by rusher** [comment]
i'm trying to reproduced the problem without success. Do you have any additional information ? 
could you confirm that those event are set with poll 'connection' event, then connection 'error' event ? something like : 
```
pool.on('connection', conn => {
      conn.on('error', (err) => {
        console.log(`connection ${conn.threadId} error `);
        console.log(err);
      })
    });
```

**Comment by rusher** [comment]
corrected with https://jira.mariadb.org/browse/CONJS-196. Will be part of 3.0.1 release

**Comment by koo5** [comment]
strange that the whole of this library's functionality somehow hinges on an undocumented requirement to run ```conn.on('error',.....``` exactly and only inside an arbitrary ```pool.on('connection'.... ``` callback?
