### ISSUE TITLE
What's the recommended way to use/change a database for a query?

### ISSUE THREAD

**Issue by CheyenneForbes** [mariadb-corporation/mariadb-connector-nodejs#197]
I'm thinking of the `multipleStatements` option and the `use` statement but the documentation warns of potential SQL injections when `multipleStatements` is enabled

**Comment by rusher** [comment]
btw, usually, if this is only for a query, the best solution is just to prefix database table, avoiding changing database at all. This will be faster. I.e. `connection.query('SELECT * FROM myDB.cart ...');` or if not known beforehand, using escapeId `` connection.query(`SELECT * FROM ${connection.escapeId(myDB)}.cart ...'); ``
