### ISSUE TITLE
Using queryStream with prepared statements

### ISSUE THREAD

**Issue by H14** [mariadb-corporation/mariadb-connector-nodejs#212]
Is it possible to use queryStream with prepared statements? 

The documentation suggests that this is not possible at the moment. Is this possibly topic for a feature request?  Or are there some technical objections?

In any case, it seems to make a lot of sense to me.

**Comment by rusher** [comment]
Implementation doesn't permit it for now. 
I've created https://jira.mariadb.org/browse/CONJS-222 in order to add that feature

**Comment by rusher** [comment]
forgot to close this. 
This is available since 3.0.2.
see documentation [here](https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/master/documentation/promise-api.md#executestreamvalues--promise)
