### ISSUE TITLE
Query logging truncates query and adds ...

### ISSUE THREAD

**Issue by nickmccally** [mariadb-corporation/mariadb-connector-nodejs#213]
I am looking to log the full query and all parameters. With a large query, I am receiving a portion of the truncated query with "..."

How can we resolve logging the full query? Logging is not useful with bits and pieces of information.

**Comment by nickmccally** [comment]
After further digging, there is a config option that is not documented: `debugLen`.

**Comment by rusher** [comment]
allright, missing documentation for debugLen and logParam option added : https://github.com/mariadb-corporation/mariadb-connector-nodejs/commit/a9228510a2717340944dddefd56fef8db17c6f08
