### ISSUE TITLE
Metadata column name gets sporadic corrupted

### ISSUE THREAD

**Issue by tjeck46** [mariadb-corporation/mariadb-connector-nodejs#215]
I have a problem with column aliases (name()) from the result metadata. If I run the same query multiple times, sometimes the names returned from meta[x].name() is corrupted, and looks like something from a memory leak. 
There seems to be a correlation between the problem and the size of the resultset, because if I set a limit in the query of fx 30 rows, there is no problem. In my case I only saw the problem when the result was more than about 300 rows.

Here is some of my code:
const r1 = await dbc.query({ rowsAsArray:true, sql:'SELECT col1, col2, col3 FROM table1', });
const cols = r1.meta.map(c => ({ name:c.name(), dataType:c.columnType }));

I'm using connector @3.0.1 and MariaDB 10.6.7 on Ubuntu. 
There seems to be no problems with version @2.5.6.

BR, Thomas

**Comment by tjeck46** [comment]
After I installed version @2.5.6 and then reinstalled @3.0.1, the problem seems to have disappered. I'm not sure if this is good or bad.. :-)

**Comment by rusher** [comment]
I think ive found the problem, but need to confirms that tomorrow

**Comment by rusher** [comment]
confirmed. This will be corrected in next version.
