### ISSUE TITLE
Malformed markdown in contributing guidelines

### ISSUE THREAD

**Issue by Jiralite** [mariadb-corporation/mariadb-connector-nodejs#221]
This repository's [contributing guidelines](https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/master/documentation/developers-guide.md) has malformed markdown, as evidently seen at the bottom.

This is easily resolved, but why does this repository not make use of the .github directory? Take a look here: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors - you would have all the wondrous features as detailed on that page.

**Comment by rusher** [comment]
Right, this has been corrected on develop branch, and so on master after next release.
