### ISSUE TITLE
FieldInfo type is missing `length` property

### ISSUE THREAD

**Issue by GingerAdonis** [mariadb-corporation/mariadb-connector-nodejs#226]
The documentation has a type-casting example like below. But the `column` argument doesn't have the `length` property typed, which is probably a mistake.
```js
const typeCastFunction = (column, next) => {
  if (column.type == "TINY" && column.length === 1) {
    const val = column.int();
    return val === null ? null : val === 1;
  }
  return next();
};
```

And a more generic question: Wouldn't it make sense to refactor the whole project to Typescript to prevent this and other typing mistakes from occurring?

**Comment by rusher** [comment]
Thanks for pointing that out, documentation has been corrected with [this](https://github.com/mariadb-corporation/mariadb-connector-nodejs/commit/f25081715c9e1f24a10017e70787108d0d2ced01) commit, see [result](https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/master/documentation/promise-api.md#typecast).

Column have no `length` property, but `columnLength`

Additionally, decoding functions have been added to documentation.

TypeScript would have been a solution at the beginning. This would be a big refactor that is not on a schedule for now.
