### ISSUE TITLE
big bundle size

### ISSUE THREAD

**Issue by outbackStack** [mariadb-corporation/mariadb-connector-nodejs#230]
Hi Guys,

Do you know why the bundle size when up so much from 3.0.1 to 3.0.2?

<img width="1325" alt="Screenshot 2023-01-28 at 1 07 50 pm" src="https://user-images.githubusercontent.com/16639496/215236598-b68e8f69-8174-4eb4-998e-9fe442f71326.png">

**Comment by rusher** [comment]
This comes from https://bundlephobia.com/package/moment-timezone size change.
3.1 futur version will get ride of moment-timzone, having a better timezone implementation, removing half of the 3.0.2 size

**Comment by outbackStack** [comment]
Amazing! Thanks @rusher 😀

<img width="1403" alt="Screenshot 2023-02-26 at 8 43 22 pm" src="https://user-images.githubusercontent.com/16639496/221403331-71b8a07b-3e6f-427f-929a-5a917c8f7b24.png">
