### ISSUE TITLE
Typescript: metaAsArray missing in QueryConfig?

### ISSUE THREAD

**Issue by MR4online** [mariadb-corporation/mariadb-connector-nodejs#231]
I think the `metaAsArray` property is missing in the `QueryConfig` interface.

The following works, but is not covered by the TypeScript definition:

```
const connection = mySqlPool.getConnection();
connection.execute({
     sql: "SELECT * FROM test WHERE id = ?",
     metaAsArray: true,
}, [1]).then(async ([results, meta]: any) => {
...
});
```

**Comment by rusher** [comment]
this will be corrected in 3.1.0 with https://github.com/mariadb-corporation/mariadb-connector-nodejs/commit/ba70356ae9485120120b57843f9157ac83145f04 commit
