### ISSUE TITLE
Typescript: supportBigNumbers & bigNumberStrings missing in ConnectionConfig

### ISSUE THREAD

**Issue by Nappsel** [mariadb-corporation/mariadb-connector-nodejs#240]
The ConnectConfig interface seems to be missing parameters `supportBigNumbers` and `bigNumberStrings`. According to the [documentation](https://mariadb.com/kb/en/nodejs-connection-options/#big-integer-support) they should be.

The following works, but is not covered by the TypeScript definition:

```
import { createConnection } from 'mariadb'

createConnection({
    host: '',
    database: '',
    user: '',
    password: '',
    supportBigNumbers: true,
  })
.then(() => {})
.catch(() => {});
```

**Comment by rusher** [comment]
Correction will be in 3.2.0 version
