### ISSUE TITLE
executing sql files

### ISSUE THREAD

**Issue by janro1** [mariadb-corporation/mariadb-connector-nodejs#242]
It would be good if the client could read sql files to restore backups for example, because in some environments it is difficult to install binaries. This is for example the case in AWS lambda.

Or maybe there is already a way that I missed in the documentation?

**Comment by rusher** [comment]
this has been implemented in 3.2.0 release . 
See importFile method : 
[without connection](https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/master/documentation/promise-api.md#importfileoptions--promise)
```javascript
try {
    await mariadb.importFile({ host: 'localhost', user: 'root', file: '/tmp/tools/data-dump.sql'});
} catch (e) {
    // ...
}
```

[with an existing connection](https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/master/documentation/promise-api.md#connectionimportfileoptions--promise)
```javascript
try {
    await conn.importFile({
        file: '/tmp/someFile.sql', 
        database: 'myDb'
    });
} catch (e) {
  // ...  
}
```

or [from a pool](https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/master/documentation/promise-api.md#poolimportfileoptions--promise):

```javascript
try {
    await pool.importFile({
        file: '/tmp/someFile.sql', 
        database: 'myDb'
    });
} catch (e) {
  // ...  
}
```
