### ISSUE TITLE
how do I remove a listener which was attached using the ConnectionPromise.on()

### ISSUE THREAD

**Issue by AkhilKamath** [mariadb-corporation/mariadb-connector-nodejs#244]
`ConnectionPromise` constructor just exposes the `.on()`, `.once()`, & `.listener()` functions of the `#conn` object. there doesn't seem a way to remove a listener that was attached using `on()`

**Comment by rusher** [comment]
All EventEmitters methods where not available on connection. This will be the case in next release

**Comment by rusher** [comment]
corrected with 3.2.0 release.

**Comment by AkhilKamath** [comment]
Hi @rusher , thanks for the updates and support of event emitter methods!
Is there a reason we are not exposing the emit() method? 
In my code I am handling connection error events but unable to write a testcase for it as I cannot forcefully call the emit method to emit an error event and test my error handling code.
