### ISSUE TITLE
logParam connection option missing from ConnectionConfig type

### ISSUE THREAD

**Issue by tommyhtran** [mariadb-corporation/mariadb-connector-nodejs#247]
logParam became documented after commit https://github.com/mariadb-corporation/mariadb-connector-nodejs/commit/a9228510a2717340944dddefd56fef8db17c6f08 (ref: #213), but was never added to ConnectionConfig.

logParam' does not exist in type 'ConnectionConfig'

**Comment by rusher** [comment]
right, this will be corrected in next version (3.2.1)

**Comment by rusher** [comment]
_closing, since released in 3.2.1_
