### ISSUE TITLE
Wrong value when doing COALESCE on bit columns

### ISSUE THREAD

**Issue by jorgen-kaxig** [mariadb-corporation/mariadb-connector-nodejs#251]
If you create a database table as in 
`CREATE TABLE coalesce_test (
    bit_a BIT,
		bit_b BIT
);`

And then insert:
`INSERT INTO coalesce_test (bit_a, bit_b) VALUES (1, 1);`

Using the mariadb package and doing the following query with COALESCE in order to get first non null value:
`SELECT COALESCE(bit_a, bit_b) AS bit_c
FROM coalesce_test;`

And then console log the result, shows:
`[ { bit_c: false } ]`

You'd expect:
`[ { bit_c: true } ]`

Have tested different versions: 3.2.0, 3.0.2

We're using 10.5.20-MariaDB on the server

**Comment by rusher** [comment]
I've created a server issue about that https://jira.mariadb.org/browse/MDEV-32244, and closing it connector side, since it's a server issue
