### ISSUE TITLE
batch result insertId should be last one or documentation should be updated

### ISSUE THREAD

**Issue by Gabilabrebi** [mariadb-corporation/mariadb-connector-nodejs#261]
Hello

When using batch for bulk insert, the insertId that get returned is the first inserted row and not the last one.

The general documentation says : "_insertId: An integer noting the auto-increment ID of the last row written to the table._" which is obviously not the case in that scenario.
I can't find anything on this particularity in the batch documentation

Regards

**Comment by rusher** [comment]
Yes, that's a documentation error, This is indeed the FIRST insert id. 
In fact, that's exactly the same than multi-values : 
```javascript
    await conn.query('CREATE TABLE ttt (ID int NOT NULL AUTO_INCREMENT PRIMARY KEY, val varchar(32))');
    const res = await conn.query("INSERT INTO ttt(val) VALUES ('a')");
    console.log(res); //OkPacket { affectedRows: 1, insertId: 1n, warningStatus: 0 }
    const res2 = await conn.query("INSERT INTO ttt(val) VALUES ('b'), ('c')");
    console.log(res2); //OkPacket { affectedRows: 2, insertId: 2n, warningStatus: 0 }
    const res3 = await conn.query("INSERT INTO ttt(val) VALUES ('d'), ('e')");
    console.log(res3); //OkPacket { affectedRows: 2, insertId: 4n, warningStatus: 0 }
```
