### ISSUE TITLE
Best option connection with PHP 8.3 

### ISSUE THREAD

**Issue by EwertonDutra** [mariadb-corporation/mariadb-connector-nodejs#264]
Hello,
sorry to post here on nodejs option
but I didn't find another mariadb project that involves php

what is the best option for me to connect php 8.3 to mariadb 10

I say version 10 because it's the one on my server

From what I can see, there are indications for using pdo and mysqli
but consulting their documentation, they don't exactly say that they are compatible with mariadb but rather with MySQL (which has differed in recent versions in some aspects of mariadb, as there is even a page on the mariadb website about the differences already)

Att

**Comment by rusher** [comment]
Closing, because stackoverflow would be a better solution for asking question like this. 
MySQL/MariaDB Protocol is the same. So connector will works all the same.
