### ISSUE TITLE
importFile throws when default database was not set

### ISSUE THREAD

**Issue by urugator** [mariadb-corporation/mariadb-connector-nodejs#266]
When `importFile` is being called with `database` option and default (current) database is not set, it throws

`TypeError: Cannot read properties of null (reading 'replace')`

https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/d0d55dccaf76af00828d877aa230147676191169/lib/connection.js#L1479

Afaik there is no way to "unuse" database, so it should probably keep using the one passed in options.

**Comment by rusher** [comment]
Thanks, reproduced and corrected. 
Too late for 3.2.3 that has just been released, but will be on next release.
