### ISSUE TITLE
Unexpected symbol 'n' in int\bigint field

### ISSUE THREAD

**Issue by codecranch** [mariadb-corporation/mariadb-connector-nodejs#271]
**"mariadb": "^3.2.3"**

```
let conn
conn = await pool.getConnection()
const rows = await conn.query("UPDATE users SET enabled = ? WHERE id = ?", [true, 1])
```
console.log(rows)
`OkPacket { affectedRows: 1, insertId: 0n, warningStatus: 0 }`

insertId: **0n**
 error : Do not know how to serialize a BigInt

Expected **0**

**Comment by rusher** [comment]
There is a specific option `insertIdAsNumber` to retrieve insertId as number.

**Comment by codecranch** [comment]
insertIdAsNumber: true

`OkPacket { affectedRows: 1, insertId: 0, warningStatus: 0 }`

Issue close / Thx
