### ISSUE TITLE
decimal values still string in result of query with decimalAsNumber true

### ISSUE THREAD

**Issue by mithrandirii** [mariadb-corporation/mariadb-connector-nodejs#278]
I found a problem with values of decimal columns in query result even if decimalAsNumber is set to true.

I think the problem is located here: https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/deca8e11198a9c07a4328c054f0f5b9095d26574/lib/cmd/decoder/text-decoder.js#L155

because Number.isSafeInteger(Number(valDec)) is always returning false if valDec is an decimal value. it's only working correctly for integer values.

how could we solve that ?

**Comment by mithrandirii** [comment]
Ping

anything missing in my issue?

**Comment by rusher** [comment]
Thanks for reporting this error, it fell through the cracks in terms of testing. This is now corrected with https://github.com/mariadb-corporation/mariadb-connector-nodejs/commit/8f88f9db129a9c8750a7603511676fb1cb573bdc . (Will be corrected in next version 3.3.0, probably release this week)

**Comment by mithrandirii** [comment]
ok, thx a lot!

**Comment by rusher** [comment]
closing since released in 3.3.0
