### ISSUE TITLE
Types: timeout in interface ConnectionConfig should be queryTimeout

### ISSUE THREAD

**Issue by Airdevelopments** [mariadb-corporation/mariadb-connector-nodejs#285]
The typing of ConnectionConfig does not seem to be up to date:

https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/d0913b46e1209016d4b6cad6841057d9cc656445/types/index.d.ts#L118

Here `timeout` should be `queryTimeout` as used in the js code: https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/d0913b46e1209016d4b6cad6841057d9cc656445/lib/config/connection-options.js#L115

Since 2.3.1
https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/master/CHANGELOG.md#231-19-mar-2020

Edit:

As it turns out there does seem to be an issue between connection-level queryTimout and query-level queryTimeout:
https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/d0913b46e1209016d4b6cad6841057d9cc656445/lib/cmd/query.js#L130

Edit 2:

I assume that `queryTimeout` as the connection-level config is correct. Then on the query-level, the `timeout` property does seem to be correct, because it does apply in SQL using the FOR-Syntax. Therefore the fix in the typing should be more nuanced (as inhertiance is used).

**Comment by rusher** [comment]
Thanks for issue and PR. 

To complete description and put some history :
Command timeout can be set at connection option level with option `queryTimeout` for all commands while a query level, this is only named `timeout`. The connection option `queryTimeout` is not just named `timeout` to avoid confusion with other timeout options, like `socketTimeout` or `connectTimeout`

problem is that Typescript description only import query options, so list `timeout` in place of `queryTimeout`.

**Comment by rusher** [comment]
closed with #286
