### ISSUE TITLE
TypeScript type definition file for SqlError constructor does not match actual constructor

### ISSUE THREAD

**Issue by jeffreyhilaire** [mariadb-corporation/mariadb-connector-nodejs#292]
Current Situation:
The [TypeScript type definition file](https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/master/types/index.d.ts#L907C1-L918C2) defines a constructor with seven (7) arguments while the [actual implementation](https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/master/lib/misc/errors.js#L8) has nine (9) arguments.

Consequence: When trying to instantiate using the mariadb.SqlError class
1. the `sql` and `cause` arguments are not visible to typescript
2. if the constructor is invoked as seen by typescript, the arguments are assigned to the wrong fields internally
3. one cannot set the cause argument at all

TypeScript constructor signature:
`interface SqlErrorConstructor extends ErrorConstructor {
  new (
    msg: string,
    fatal?: boolean,
    info?: { threadId?: number },
    sqlState?: string | null,
    errno?: number,
    additionalStack?: string,
    addHeader?: boolean
  ): SqlError;
  readonly prototype: SqlError;
}`

Actual Implementation: `constructor(msg, sql, fatal, info, sqlState, errno, additionalStack, addHeader = undefined, cause)`

**Comment by rusher** [comment]
i forgot to add this issue prefix to commit : it has been part of 3.3.2 release with commit https://github.com/mariadb-corporation/mariadb-connector-nodejs/commit/e439eb1a4f49d934a38bdcabc3b5bd9f4ea3815c
