### ISSUE TITLE
Stored Procedure Calls

### ISSUE THREAD

**Issue by fathert** [mariadb-corporation/mariadb-connector-nodejs#90]
I can't see any way at the moment to call stored procedures and to access the parameters returned. Would it be possible to support this in a future release?

**Comment by rusher** [comment]
There is no way to do that in a simple command for now. 
I've created a [task](https://jira.mariadb.org/projects/CONJS/issues/CONJS-113) to implement that. 

The best way to do that seems  to defined the output parameters as user-defined variables and retrieving them afterwhile.
here is one example : 
```js
//CREATE OR REPLACE PROCEDURE someProc (IN p1 INT, OUT p2 INT)
// begin set p2 = p1 * 2; end

con.query('call multiplyBy2(?,@myOutputValue)', [2])
      .then(() => {
        return con.query('SELECT @myOutputValue')
      })
      .then(rows => {
        console.log(rows); //[ { '@myOutputValue': 4 } ]
      })
      .catch(...)

```

**Comment by fathert** [comment]
Ah, that's an idea! Thanks.

**Comment by rusher** [comment]
[Documentation added](https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/maintenance/3.x/documentation/promise-api.md#stored-procedure-with-output-parameter)
