### ISSUE TITLE
ER_DUP_ENTRY - Named unique index not accessible

### ISSUE THREAD

**Issue by y0x** [mariadb-corporation/mariadb-connector-nodejs#91]
Hi,

would it be possible to make the "key" value more accessible in case an error is returned while failing on `code: 'ER_DUP_ENTRY'`.

Currently, i´m only able to easily check against the error.code ER_DUP_ENTRY, but it would be even better if i could easily read out the real reason for failing, which is currently just returned in a string like here: `SQLError: (conn=388, no: 1062, SQLState: 23000) Duplicate entry 'a' for key 'short_url'`. Or do i miss something?

This would benefit a lot in case you have a big table with more than one unique index and you would like to inform the user on that. With the postgres driver i was able to use code like this e.g:

 ```
 if (error.code === "ER_DUP_ENTRY") {
       switch (error.constraint) {
        case "short_url":
                 //inform user
          break;
   case "anotherUniqueIndex":
                 //inform user
          break;
      } 
 }
```
Would be great if you could add such functionality to this awesome lib.

Thanks.

**Comment by rusher** [comment]
MariaDB (and MySQL) just return a human-readable error string, SQLState and error code (see https://mariadb.com/kb/en/library/err_packet/) following SQL standard (https://en.wikipedia.org/wiki/SQLSTATE)

There is actually no possibility for a MySQL/MariaDB connector to provide that information. 
Even if I tend to agree that it's always better to have good informations, client already has lots of informations. 

If you think this is a really important, fell free to create a jira request to server: https://jira.mariadb.org/projects/MDEV/

**Comment by y0x** [comment]
Interesting fact, thanks for pointing that out. I didn´t expected that it´s just not possible with MySQL/MariaDB.

Yes I agree that there a lot of information returned, but in case you provide a user a formula with 6 inputs and 2 of them must be unique, it requires extra effort to present the user a good looking and formulated information on the frontend. That´s definitely a thing that was cleaner to solve using postgres. 

However, thanks for your work and the quick reply to my question!

**Comment by vaintroub** [comment]
Why would you expect error information to be structured generally? No protocol or standardized API require that. So this could just be a Postgres tweak, accessible from only that specific node.js driver. Not to say it is not useful, but it is highly non-portable.
