### ISSUE TITLE
Package requires @types/node 13 but minimum required node version is 8.1

### ISSUE THREAD

**Issue by SimonSchick** [mariadb-corporation/mariadb-connector-nodejs#98]
This is not a huge deal but it should probably require @types/node>=8 otherwise a codebase that is still on v10 or v12 will install the typings twice.

Basically the same as https://github.com/stripe/stripe-node/issues/783

**Comment by rusher** [comment]
right ! this is done in https://github.com/mariadb-corporation/mariadb-connector-nodejs/commit/92962b12b82afc17c0513f9ab6ee61d32f3c33d3 and will be released in next version
